// <auto-generated />
using System;
using GuvenOto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuvenOto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409103146_AddUserAndDateToIlan")]
    partial class AddUserAndDateToIlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AracHasarKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DamageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DamageReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHeavyDamage")
                        .HasColumnType("bit");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleDamageRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12500.0,
                            DamageDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DamageReason = "Carpisma hasari.",
                            IsHeavyDamage = false,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 85000.0,
                            DamageDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DamageReason = "Agir Hasar kaydi.",
                            IsHeavyDamage = true,
                            Plate = "57ED244"
                        });
                });

            modelBuilder.Entity("AracMuayene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KilometerAtInspection")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleInspections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "Sinop Merkez",
                            KilometerAtInspection = 185000,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "Sinop Boyabat",
                            KilometerAtInspection = 240000,
                            Plate = "57ED244"
                        });
                });

            modelBuilder.Entity("AracRuhsat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleRegistries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChassisNumber = "SASI-ED-9988",
                            EngineNumber = "MOTOR-ED-1122",
                            OwnerName = "Ahmet Yılmaz",
                            Plate = "57ED244",
                            RegistrationDate = new DateTime(2015, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleColor = "Beyaz"
                        },
                        new
                        {
                            Id = 2,
                            ChassisNumber = "SASI-AA-3322",
                            EngineNumber = "MOTOR-AA-5544",
                            OwnerName = "Mehmet Demir",
                            Plate = "57AAR642",
                            RegistrationDate = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleColor = "Metalik Gri"
                        });
                });

            modelBuilder.Entity("GuvenOto.Models.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracModeliId")
                        .HasColumnType("int")
                        .HasColumnName("ModelId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometer")
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int")
                        .HasColumnName("BrandId");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracModeliId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars", null, t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("ModelId1");
                        });
                });

            modelBuilder.Entity("GuvenOto.Models.AracModeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarkaId")
                        .HasColumnType("int")
                        .HasColumnName("BrandId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ParentModelId");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Ilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracModeliId")
                        .HasColumnType("int")
                        .HasColumnName("ModelId");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("DistrictId");

                    b.Property<string>("ExpertisePdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrontBumperStatus")
                        .HasColumnType("int");

                    b.Property<int>("FrontLeftDoor")
                        .HasColumnType("int");

                    b.Property<int>("FrontLeftFender")
                        .HasColumnType("int");

                    b.Property<int>("FrontRightDoor")
                        .HasColumnType("int");

                    b.Property<int>("FrontRightFender")
                        .HasColumnType("int");

                    b.Property<int>("HoodStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kilometer")
                        .HasColumnType("int");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RearBumperStatus")
                        .HasColumnType("int");

                    b.Property<int>("RearLeftDoor")
                        .HasColumnType("int");

                    b.Property<int>("RearLeftFender")
                        .HasColumnType("int");

                    b.Property<int>("RearRightDoor")
                        .HasColumnType("int");

                    b.Property<int>("RearRightFender")
                        .HasColumnType("int");

                    b.Property<int>("RoofStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrunkStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracModeliId");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.IlanOzellikDegeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("OzellikId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("OzellikId");

                    b.ToTable("ListingFeatureValues", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Ozellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FormatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("GuvenOto.Models.Araba", b =>
                {
                    b.HasOne("GuvenOto.Models.AracModeli", "AracModeli")
                        .WithMany()
                        .HasForeignKey("AracModeliId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.AracModeli", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracModeli");

                    b.Navigation("Marka");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GuvenOto.Models.AracModeli", b =>
                {
                    b.HasOne("GuvenOto.Models.Marka", "Marka")
                        .WithMany("Models")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.AracModeli", "ParentModel")
                        .WithMany("SubModels")
                        .HasForeignKey("ParentModelId");

                    b.Navigation("Marka");

                    b.Navigation("ParentModel");
                });

            modelBuilder.Entity("GuvenOto.Models.Ilan", b =>
                {
                    b.HasOne("GuvenOto.Models.AracModeli", "AracModeli")
                        .WithMany("Ilanlar")
                        .HasForeignKey("AracModeliId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AracModeli");

                    b.Navigation("Ilce");

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("GuvenOto.Models.IlanOzellikDegeri", b =>
                {
                    b.HasOne("GuvenOto.Models.Ilan", "Ilan")
                        .WithMany("IlanOzellikDegeri")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Ozellik", "Ozellik")
                        .WithMany()
                        .HasForeignKey("OzellikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Ozellik");
                });

            modelBuilder.Entity("GuvenOto.Models.Ilce", b =>
                {
                    b.HasOne("GuvenOto.Models.Sehir", "Sehir")
                        .WithMany("Ilceler")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("GuvenOto.Models.Sehir", b =>
                {
                    b.HasOne("GuvenOto.Models.Bolge", "Bolge")
                        .WithMany("Sehirler")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("GuvenOto.Models.AracModeli", b =>
                {
                    b.Navigation("Ilanlar");

                    b.Navigation("SubModels");
                });

            modelBuilder.Entity("GuvenOto.Models.Bolge", b =>
                {
                    b.Navigation("Sehirler");
                });

            modelBuilder.Entity("GuvenOto.Models.Ilan", b =>
                {
                    b.Navigation("IlanOzellikDegeri");
                });

            modelBuilder.Entity("GuvenOto.Models.Marka", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("GuvenOto.Models.Sehir", b =>
                {
                    b.Navigation("Ilceler");
                });
#pragma warning restore 612, 618
        }
    }
}
