// <auto-generated />
using System;
using GuvenOto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuvenOto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404115239_SeedVehicleSimulation")]
    partial class SeedVehicleSimulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuvenOto.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("GuvenOto.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometer")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("GuvenOto.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FormatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("GuvenOto.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertisePdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrontBumperStatus")
                        .HasColumnType("int");

                    b.Property<int>("FrontLeftDoor")
                        .HasColumnType("int");

                    b.Property<int>("FrontLeftFender")
                        .HasColumnType("int");

                    b.Property<int>("FrontRightDoor")
                        .HasColumnType("int");

                    b.Property<int>("FrontRightFender")
                        .HasColumnType("int");

                    b.Property<int>("HoodStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kilometer")
                        .HasColumnType("int");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RearBumperStatus")
                        .HasColumnType("int");

                    b.Property<int>("RearLeftDoor")
                        .HasColumnType("int");

                    b.Property<int>("RearLeftFender")
                        .HasColumnType("int");

                    b.Property<int>("RearRightDoor")
                        .HasColumnType("int");

                    b.Property<int>("RearRightFender")
                        .HasColumnType("int");

                    b.Property<int>("RoofStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrunkStatus")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("GuvenOto.Models.ListingFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingFeatureValues");
                });

            modelBuilder.Entity("GuvenOto.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ParentModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("GuvenOto.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleDamageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DamageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DamageReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHeavyDamage")
                        .HasColumnType("bit");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleDamageRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12500.0,
                            DamageDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DamageReason = "Mesaj: Sayin ilgili, 57ED244 plakali arac 12.03.2019 tarihinde 'Carpisma' nedeniyle 12.500 TL hasar kaydi almistir.",
                            IsHeavyDamage = false,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 85000.0,
                            DamageDate = new DateTime(2022, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DamageReason = "Mesaj: Sayin ilgili, 57ED244 plakali arac 05.10.2022 tarihinde 'Agir Hasar' (Pert) kaydi almistir. Tutar: 85.000 TL",
                            IsHeavyDamage = true,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4200.0,
                            DamageDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DamageReason = "Mesaj: Sayin ilgili, 57AAR642 plakali arac 20.08.2023 tarihinde 'Park Halinde Carpilma' nedeniyle 4.200 TL hasar kaydi almistir.",
                            IsHeavyDamage = false,
                            Plate = "57AAR642"
                        });
                });

            modelBuilder.Entity("VehicleInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KilometerAtInspection")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleInspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "Sinop Merkez",
                            KilometerAtInspection = 185000,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "Sinop Boyabat",
                            KilometerAtInspection = 240000,
                            Plate = "57ED244"
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "İstanbul Dudullu",
                            KilometerAtInspection = 35000,
                            Plate = "57AAR642"
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionStation = "Sinop Merkez",
                            KilometerAtInspection = 72000,
                            Plate = "57AAR642"
                        });
                });

            modelBuilder.Entity("VehicleRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleRegistries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChassisNumber = "SASI-ED-9988",
                            EngineNumber = "MOTOR-ED-1122",
                            OwnerName = "Ahmet Yılmaz",
                            Plate = "57ED244",
                            RegistrationDate = new DateTime(2015, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleColor = "Beyaz"
                        },
                        new
                        {
                            Id = 2,
                            ChassisNumber = "SASI-AA-3322",
                            EngineNumber = "MOTOR-AA-5544",
                            OwnerName = "Mehmet Demir",
                            Plate = "57AAR642",
                            RegistrationDate = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleColor = "Metalik Gri"
                        });
                });

            modelBuilder.Entity("GuvenOto.Models.Car", b =>
                {
                    b.HasOne("GuvenOto.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GuvenOto.Models.Listing", b =>
                {
                    b.HasOne("GuvenOto.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GuvenOto.Models.ListingFeatureValue", b =>
                {
                    b.HasOne("GuvenOto.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Listing", "Listing")
                        .WithMany("FeatureValues")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("GuvenOto.Models.Model", b =>
                {
                    b.HasOne("GuvenOto.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenOto.Models.Model", "ParentModel")
                        .WithMany("SubModels")
                        .HasForeignKey("ParentModelId");

                    b.Navigation("Brand");

                    b.Navigation("ParentModel");
                });

            modelBuilder.Entity("GuvenOto.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("GuvenOto.Models.Listing", b =>
                {
                    b.Navigation("FeatureValues");
                });

            modelBuilder.Entity("GuvenOto.Models.Model", b =>
                {
                    b.Navigation("SubModels");
                });
#pragma warning restore 612, 618
        }
    }
}
